# Generated by Django 3.0.6 on 2020-05-20 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DireccionCliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=9, verbose_name='Teléfono')),
                ('ciudad', models.CharField(max_length=200, verbose_name='Ciudad')),
                ('direccion', models.CharField(max_length=1024, verbose_name='Dirección')),
                ('anotaciones', models.CharField(max_length=1024, verbose_name='Dirección')),
                ('codigo_postal', models.CharField(max_length=12, verbose_name='Código Postal')),
            ],
        ),
        migrations.CreateModel(
            name='DireccionEmpresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=9, verbose_name='Teléfono')),
                ('ciudad', models.CharField(max_length=200, verbose_name='Ciudad')),
                ('direccion', models.CharField(max_length=1024, verbose_name='Dirección')),
                ('anotaciones', models.CharField(max_length=1024, verbose_name='Dirección')),
                ('codigo_postal', models.CharField(max_length=12, verbose_name='Código Postal')),
            ],
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='nombre',
            new_name='nombre_empresa',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='codigo_postal',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='codigo_postal',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='email',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='telefono',
        ),
        migrations.AddField(
            model_name='empresa',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.AddField(
            model_name='direccionempresa',
            name='cliente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='direccion_empresa', to='usuarios.Empresa'),
        ),
        migrations.AddField(
            model_name='direccioncliente',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcciones_cliente', to='usuarios.Cliente'),
        ),
    ]
