# Generated by Django 3.0.6 on 2020-05-21 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20200520_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='direccioncliente',
            name='modificable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='direccioncliente',
            name='nombre_direccion',
            field=models.CharField(default='', max_length=50, verbose_name='Nombre Direccion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='direccionempresa',
            name='modificable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='direccionempresa',
            name='nombre_direccion',
            field=models.CharField(default='', max_length=50, verbose_name='Nombre Direccion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nombre_empresa',
            field=models.CharField(default='', max_length=100, verbose_name='Nombre Empresa'),
        ),
    ]
