# Generated by Django 3.0.6 on 2020-05-25 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20200521_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='cp_list',
            field=models.TextField(default='[]', verbose_name='Listado Codigos postales disponibles'),
        ),
    ]
