# Generated by Django 3.0.6 on 2020-05-25 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0004_empresa_cp_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='cp_list',
        ),
        migrations.AddField(
            model_name='cliente',
            name='id_empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Empresa', to='usuarios.Empresa'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='id_empresa',
            field=models.CharField(default='', max_length=100, verbose_name='Nombre Empresa'),
        ),
        migrations.CreateModel(
            name='EmpresaComida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(default='', max_length=100, verbose_name='Nombre Empresa')),
                ('cp_list', models.TextField(default='[]', verbose_name='Listado Codigos postales disponibles')),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
