# Generated by Django 3.0.6 on 2020-05-25 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_auto_20200525_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='metodo_pago',
            field=models.CharField(choices=[('TARJETA', 'Pago con tarjeta al recoger el pedido'), ('EFECTIVO', 'Pago en efectivo al recoger el pedido')], default='EFECTIVO', max_length=30),
        ),
        migrations.AddField(
            model_name='cliente',
            name='notificaciones',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='direccionempresa',
            name='anotaciones',
            field=models.CharField(max_length=1024, verbose_name='Información Extra'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='id_empresa',
            field=models.CharField(default='', max_length=100, verbose_name='Id Empresa'),
        ),
    ]
