# Generated by Django 3.0.6 on 2020-05-26 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_auto_20200525_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='direccion_defecto',
            field=models.IntegerField(default=0),
        ),
    ]
