# Generated by Django 3.0.6 on 2020-05-26 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_cliente_direccion_defecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='id_empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Empresa', to='usuarios.Empresa'),
        ),
    ]
