# Generated by Django 3.0.6 on 2020-05-21 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comidas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/recetas/'),
        ),
    ]
