# Generated by Django 3.0.6 on 2020-05-25 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_auto_20200525_0942'),
        ('comidas', '0002_receta_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.EmpresaComida'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.EmpresaComida'),
        ),
    ]
