# Generated by Django 3.0.6 on 2020-05-27 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comidas', '0003_auto_20200525_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentemenu',
            name='precio',
            field=models.DecimalField(decimal_places=1, default=3.5, editable=False, max_digits=4),
        ),
    ]
