# Generated by Django 3.0.6 on 2020-05-28 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comidas', '0004_componentemenu_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='descripcion',
            field=models.TextField(default=''),
        ),
    ]
