# Generated by Django 3.0.6 on 2020-05-28 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comidas', '0005_receta_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alergenos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('icono', models.CharField(max_length=128)),
                ('color', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='receta',
            name='alergenos',
            field=models.ManyToManyField(to='comidas.Alergenos'),
        ),
    ]
