# Generated by Django 3.0.6 on 2020-05-28 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comidas', '0006_auto_20200528_0746'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Alergenos',
            new_name='Alergeno',
        ),
    ]
