# Generated by Django 3.0.6 on 2020-05-28 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comidas', '0007_auto_20200528_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='alergeno',
            name='libreria',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
