# Generated by Django 3.0.6 on 2020-05-28 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comidas', '0008_alergeno_libreria'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='peso_porcion',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='receta',
            name='alergenos',
            field=models.ManyToManyField(blank=True, null=True, to='comidas.Alergeno'),
        ),
    ]
