# Generated by Django 3.0.6 on 2020-05-29 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comidas', '0009_auto_20200528_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentemenu',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=3.5, max_digits=4),
        ),
    ]
