# Generated by Django 3.0.4 on 2020-04-01 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatoNutricional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('tipo', models.CharField(max_length=20)),
                ('unidad', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('unidad', models.CharField(max_length=20)),
                ('equivalencia_en_gramos', models.FloatField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='InfoNutricional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('cantidad', models.FloatField()),
                ('dato_nutricional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingredientes.DatoNutricional')),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datos_nutricionales', to='ingredientes.Ingrediente')),
            ],
        ),
    ]
