# Generated by Django 3.0.6 on 2020-05-21 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comidas', '0002_receta_imagen'),
        ('usuarios', '0003_auto_20200521_0850'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineaPedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raciones', models.IntegerField(default=1)),
                ('facturado', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Cliente')),
                ('direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.DireccionCliente')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comidas.ComponenteMenu')),
            ],
        ),
    ]
