# Generated by Django 3.0.6 on 2020-05-29 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_auto_20200526_2018'),
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineapedido',
            name='direccion',
        ),
        migrations.AddField(
            model_name='lineapedido',
            name='direccion_cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.DireccionCliente'),
        ),
        migrations.AddField(
            model_name='lineapedido',
            name='direccion_empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.DireccionEmpresa'),
        ),
    ]
